--
-- PostgreSQL database dump
--

\restrict e9vjYABteOfhgXdn3CsQI1lhAlMraOpB2SEKCwimllYk1HYVd3IKkAGpc7B0tw6

-- Dumped from database version 16.14
-- Dumped by pg_dump version 16.14

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.accounts (
    id bigint NOT NULL,
    account_number character varying(20) NOT NULL,
    account_type character varying(255) NOT NULL,
    balance numeric(18,2) NOT NULL,
    created_at timestamp(6) without time zone,
    is_active boolean NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    account_name character varying(100),
    branch character varying(255),
    currency character varying(3),
    CONSTRAINT accounts_account_type_check CHECK (((account_type)::text = ANY ((ARRAY['CHECKING'::character varying, 'SAVINGS'::character varying])::text[])))
);


ALTER TABLE public.accounts OWNER TO postgres;

--
-- Name: accounts_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.accounts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cards; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cards (
    id bigint NOT NULL,
    available_balance numeric(18,2),
    card_brand character varying(255) NOT NULL,
    card_holder_name character varying(100) NOT NULL,
    card_number character varying(20) NOT NULL,
    card_tier character varying(255) NOT NULL,
    card_type character varying(255) NOT NULL,
    created_at timestamp(6) without time zone,
    credit_limit numeric(18,2),
    expiry_date character varying(5) NOT NULL,
    linked_account_number character varying(20),
    status character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    used_amount numeric(18,2),
    user_id bigint NOT NULL,
    CONSTRAINT cards_card_brand_check CHECK (((card_brand)::text = ANY ((ARRAY['VISA'::character varying, 'MASTERCARD'::character varying, 'JCB'::character varying, 'NAPAS'::character varying])::text[]))),
    CONSTRAINT cards_card_tier_check CHECK (((card_tier)::text = ANY ((ARRAY['STANDARD'::character varying, 'GOLD'::character varying, 'PLATINUM'::character varying, 'SIGNATURE'::character varying, 'INFINITE'::character varying])::text[]))),
    CONSTRAINT cards_card_type_check CHECK (((card_type)::text = ANY ((ARRAY['DEBIT'::character varying, 'CREDIT'::character varying])::text[]))),
    CONSTRAINT cards_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'LOCKED'::character varying, 'EXPIRED'::character varying, 'CANCELLED'::character varying])::text[])))
);


ALTER TABLE public.cards OWNER TO postgres;

--
-- Name: cards_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.cards ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cards_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: loans; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.loans (
    id bigint NOT NULL,
    collateral character varying(255),
    created_at timestamp(6) without time zone,
    end_date date NOT NULL,
    interest_rate numeric(5,2) NOT NULL,
    linked_account_number character varying(20),
    loan_amount numeric(18,2) NOT NULL,
    loan_code character varying(20) NOT NULL,
    loan_type character varying(255) NOT NULL,
    monthly_payment numeric(18,2) NOT NULL,
    next_payment_date date NOT NULL,
    remaining_balance numeric(18,2) NOT NULL,
    start_date date NOT NULL,
    status character varying(255) NOT NULL,
    term_months integer NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT loans_loan_type_check CHECK (((loan_type)::text = ANY ((ARRAY['PERSONAL'::character varying, 'MORTGAGE'::character varying, 'BUSINESS'::character varying, 'CAR_LOAN'::character varying])::text[]))),
    CONSTRAINT loans_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'PAID_OFF'::character varying, 'OVERDUE'::character varying, 'PENDING'::character varying])::text[])))
);


ALTER TABLE public.loans OWNER TO postgres;

--
-- Name: loans_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.loans ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.loans_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notifications; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.notifications (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    is_read boolean NOT NULL,
    message text NOT NULL,
    related_entity_id bigint,
    related_entity_type character varying(50),
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT notifications_type_check CHECK (((type)::text = ANY ((ARRAY['TRANSACTION'::character varying, 'SECURITY'::character varying, 'PROMOTION'::character varying, 'SYSTEM'::character varying])::text[])))
);


ALTER TABLE public.notifications OWNER TO postgres;

--
-- Name: notifications_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.notifications ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notifications_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: savings; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.savings (
    id bigint NOT NULL,
    amount numeric(18,2) NOT NULL,
    auto_renew character varying(10),
    created_at timestamp(6) without time zone,
    interest_rate numeric(5,2) NOT NULL,
    linked_account_number character varying(20),
    maturity_date date NOT NULL,
    saving_code character varying(20) NOT NULL,
    saving_name character varying(100),
    start_date date NOT NULL,
    status character varying(255) NOT NULL,
    term_months integer NOT NULL,
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL,
    CONSTRAINT savings_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'MATURED'::character varying, 'WITHDRAWN'::character varying])::text[])))
);


ALTER TABLE public.savings OWNER TO postgres;

--
-- Name: savings_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.savings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.savings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    amount numeric(18,2) NOT NULL,
    balance_after numeric(18,2),
    balance_before numeric(18,2),
    created_at timestamp(6) without time zone,
    description character varying(255),
    reference_code character varying(30) NOT NULL,
    status character varying(255) NOT NULL,
    transaction_type character varying(255) NOT NULL,
    destination_account_id bigint,
    source_account_id bigint,
    destination_bank character varying(100),
    destination_name character varying(100),
    CONSTRAINT transactions_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'COMPLETED'::character varying, 'FAILED'::character varying])::text[]))),
    CONSTRAINT transactions_transaction_type_check CHECK (((transaction_type)::text = ANY ((ARRAY['DEPOSIT'::character varying, 'WITHDRAWAL'::character varying, 'TRANSFER'::character varying])::text[])))
);


ALTER TABLE public.transactions OWNER TO postgres;

--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone,
    email character varying(100) NOT NULL,
    full_name character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    password character varying(255) NOT NULL,
    phone_number character varying(15),
    role character varying(255) NOT NULL,
    updated_at timestamp(6) without time zone,
    username character varying(50) NOT NULL,
    address character varying(255),
    avatar_url character varying(255),
    date_of_birth date,
    id_number character varying(20),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['USER'::character varying, 'ADMIN'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.accounts (id, account_number, account_type, balance, created_at, is_active, updated_at, user_id, account_name, branch, currency) FROM stdin;
3	MB0123456789	CHECKING	125750000.00	2026-07-24 13:41:44.71163	t	2026-07-24 13:41:44.71163	2	\N	\N	VND
4	MB9876543210	SAVINGS	450000000.00	2026-07-24 13:41:44.71363	t	2026-07-24 13:41:44.71363	2	\N	\N	VND
\.


--
-- Data for Name: cards; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cards (id, available_balance, card_brand, card_holder_name, card_number, card_tier, card_type, created_at, credit_limit, expiry_date, linked_account_number, status, updated_at, used_amount, user_id) FROM stdin;
4	\N	VISA	LE KHANH NGOC	4123456789012345	PLATINUM	DEBIT	2026-07-24 13:41:44.715627	\N	12/28	MB0123456789	ACTIVE	2026-07-24 13:41:44.715627	0.00	2
5	75000000.00	MASTERCARD	LE KHANH NGOC	5123456789012345	GOLD	CREDIT	2026-07-24 13:41:44.71763	100000000.00	10/27	\N	ACTIVE	2026-07-24 13:41:44.71763	25000000.00	2
6	\N	JCB	LE KHANH NGOC	3528456789012345	STANDARD	DEBIT	2026-07-24 13:41:44.71863	\N	05/26	MB9876543210	LOCKED	2026-07-24 13:41:44.71863	0.00	2
\.


--
-- Data for Name: loans; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.loans (id, collateral, created_at, end_date, interest_rate, linked_account_number, loan_amount, loan_code, loan_type, monthly_payment, next_payment_date, remaining_balance, start_date, status, term_months, updated_at, user_id) FROM stdin;
3	\N	2026-07-24 13:41:44.724537	2034-07-24	8.50	MB0123456789	1500000000.00	LN202501	MORTGAGE	18500000.00	2026-08-08	1200000000.00	2024-07-24	ACTIVE	120	2026-07-24 13:41:44.724537	2
4	\N	2026-07-24 13:41:44.726535	2027-09-24	12.00	MB0123456789	50000000.00	LN202601	PERSONAL	2350000.00	2026-07-29	25000000.00	2025-09-24	ACTIVE	24	2026-07-24 13:41:44.726535	2
\.


--
-- Data for Name: notifications; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.notifications (id, created_at, is_read, message, related_entity_id, related_entity_type, title, type, user_id) FROM stdin;
11	2026-07-24 13:41:44.763481	t	Chi tiết thông báo số 1 dành cho bạn.	\N	\N	Thông báo 1	PROMOTION	2
12	2026-07-24 13:41:44.765489	t	Chi tiết thông báo số 2 dành cho bạn.	\N	\N	Thông báo 2	TRANSACTION	2
13	2026-07-24 13:41:44.766486	t	Chi tiết thông báo số 3 dành cho bạn.	\N	\N	Thông báo 3	PROMOTION	2
14	2026-07-24 13:41:44.766486	f	Chi tiết thông báo số 4 dành cho bạn.	\N	\N	Thông báo 4	TRANSACTION	2
15	2026-07-24 13:41:44.767489	f	Chi tiết thông báo số 5 dành cho bạn.	\N	\N	Thông báo 5	PROMOTION	2
16	2026-07-24 13:41:44.767489	f	Chi tiết thông báo số 6 dành cho bạn.	\N	\N	Thông báo 6	TRANSACTION	2
17	2026-07-24 13:41:44.768486	f	Chi tiết thông báo số 7 dành cho bạn.	\N	\N	Thông báo 7	PROMOTION	2
18	2026-07-24 13:41:44.768486	f	Chi tiết thông báo số 8 dành cho bạn.	\N	\N	Thông báo 8	TRANSACTION	2
19	2026-07-24 13:41:44.769603	f	Chi tiết thông báo số 9 dành cho bạn.	\N	\N	Thông báo 9	PROMOTION	2
20	2026-07-24 13:41:44.769603	f	Chi tiết thông báo số 10 dành cho bạn.	\N	\N	Thông báo 10	TRANSACTION	2
\.


--
-- Data for Name: savings; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.savings (id, amount, auto_renew, created_at, interest_rate, linked_account_number, maturity_date, saving_code, saving_name, start_date, status, term_months, updated_at, user_id) FROM stdin;
3	200000000.00	YES	2026-07-24 13:41:44.720421	5.50	MB0123456789	2026-11-24	SV202601	Tiết kiệm mua nhà	2026-05-24	ACTIVE	6	2026-07-24 13:41:44.720421	2
4	250000000.00	YES	2026-07-24 13:41:44.722426	6.80	MB0123456789	2027-02-24	SV202602	Tiết kiệm dài hạn	2026-02-24	ACTIVE	12	2026-07-24 13:41:44.722426	2
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transactions (id, amount, balance_after, balance_before, created_at, description, reference_code, status, transaction_type, destination_account_id, source_account_id, destination_bank, destination_name) FROM stdin;
41	500000.00	129500000.00	130000000.00	2026-07-24 13:41:44.729535	Chuyển khoản 1	TXN202607002	COMPLETED	TRANSFER	\N	3	\N	\N
42	1000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.732768	Nhận tiền 1	TXN202607003	COMPLETED	DEPOSIT	3	\N	\N	\N
43	1000000.00	129500000.00	130000000.00	2026-07-24 13:41:44.734103	Chuyển khoản 2	TXN202607004	COMPLETED	TRANSFER	\N	3	\N	\N
44	2000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.735111	Nhận tiền 2	TXN202607005	COMPLETED	DEPOSIT	3	\N	\N	\N
45	1500000.00	129500000.00	130000000.00	2026-07-24 13:41:44.735111	Chuyển khoản 3	TXN202607006	COMPLETED	TRANSFER	\N	3	\N	\N
46	3000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.736679	Nhận tiền 3	TXN202607007	COMPLETED	DEPOSIT	3	\N	\N	\N
47	2000000.00	129500000.00	130000000.00	2026-07-24 13:41:44.737688	Chuyển khoản 4	TXN202607008	COMPLETED	TRANSFER	\N	3	\N	\N
48	4000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.738685	Nhận tiền 4	TXN202607009	COMPLETED	DEPOSIT	3	\N	\N	\N
49	2500000.00	129500000.00	130000000.00	2026-07-24 13:41:44.739842	Chuyển khoản 5	TXN202607010	COMPLETED	TRANSFER	\N	3	\N	\N
50	5000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.739842	Nhận tiền 5	TXN202607011	COMPLETED	DEPOSIT	3	\N	\N	\N
51	3000000.00	129500000.00	130000000.00	2026-07-24 13:41:44.740841	Chuyển khoản 6	TXN202607012	COMPLETED	TRANSFER	\N	3	\N	\N
52	6000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.741841	Nhận tiền 6	TXN202607013	COMPLETED	DEPOSIT	3	\N	\N	\N
53	3500000.00	129500000.00	130000000.00	2026-07-24 13:41:44.743127	Chuyển khoản 7	TXN202607014	COMPLETED	TRANSFER	\N	3	\N	\N
54	7000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.743127	Nhận tiền 7	TXN202607015	COMPLETED	DEPOSIT	3	\N	\N	\N
55	4000000.00	129500000.00	130000000.00	2026-07-24 13:41:44.74457	Chuyển khoản 8	TXN202607016	COMPLETED	TRANSFER	\N	3	\N	\N
56	8000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.745579	Nhận tiền 8	TXN202607017	COMPLETED	DEPOSIT	3	\N	\N	\N
57	4500000.00	129500000.00	130000000.00	2026-07-24 13:41:44.745579	Chuyển khoản 9	TXN202607018	COMPLETED	TRANSFER	\N	3	\N	\N
58	9000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.746577	Nhận tiền 9	TXN202607019	COMPLETED	DEPOSIT	3	\N	\N	\N
59	5000000.00	129500000.00	130000000.00	2026-07-24 13:41:44.747924	Chuyển khoản 10	TXN202607020	COMPLETED	TRANSFER	\N	3	\N	\N
60	10000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.747924	Nhận tiền 10	TXN202607021	COMPLETED	DEPOSIT	3	\N	\N	\N
61	5500000.00	129500000.00	130000000.00	2026-07-24 13:41:44.748931	Chuyển khoản 11	TXN202607022	COMPLETED	TRANSFER	\N	3	\N	\N
62	11000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.748931	Nhận tiền 11	TXN202607023	COMPLETED	DEPOSIT	3	\N	\N	\N
63	6000000.00	129500000.00	130000000.00	2026-07-24 13:41:44.75007	Chuyển khoản 12	TXN202607024	COMPLETED	TRANSFER	\N	3	\N	\N
64	12000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.751072	Nhận tiền 12	TXN202607025	COMPLETED	DEPOSIT	3	\N	\N	\N
65	6500000.00	129500000.00	130000000.00	2026-07-24 13:41:44.751072	Chuyển khoản 13	TXN202607026	COMPLETED	TRANSFER	\N	3	\N	\N
66	13000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.752503	Nhận tiền 13	TXN202607027	COMPLETED	DEPOSIT	3	\N	\N	\N
67	7000000.00	129500000.00	130000000.00	2026-07-24 13:41:44.75351	Chuyển khoản 14	TXN202607028	COMPLETED	TRANSFER	\N	3	\N	\N
68	14000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.75351	Nhận tiền 14	TXN202607029	COMPLETED	DEPOSIT	3	\N	\N	\N
69	7500000.00	129500000.00	130000000.00	2026-07-24 13:41:44.75451	Chuyển khoản 15	TXN202607030	COMPLETED	TRANSFER	\N	3	\N	\N
70	15000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.75551	Nhận tiền 15	TXN202607031	COMPLETED	DEPOSIT	3	\N	\N	\N
71	8000000.00	129500000.00	130000000.00	2026-07-24 13:41:44.75551	Chuyển khoản 16	TXN202607032	COMPLETED	TRANSFER	\N	3	\N	\N
72	16000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.756511	Nhận tiền 16	TXN202607033	COMPLETED	DEPOSIT	3	\N	\N	\N
73	8500000.00	129500000.00	130000000.00	2026-07-24 13:41:44.756511	Chuyển khoản 17	TXN202607034	COMPLETED	TRANSFER	\N	3	\N	\N
74	17000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.757951	Nhận tiền 17	TXN202607035	COMPLETED	DEPOSIT	3	\N	\N	\N
75	9000000.00	129500000.00	130000000.00	2026-07-24 13:41:44.757951	Chuyển khoản 18	TXN202607036	COMPLETED	TRANSFER	\N	3	\N	\N
76	18000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.759428	Nhận tiền 18	TXN202607037	COMPLETED	DEPOSIT	3	\N	\N	\N
77	9500000.00	129500000.00	130000000.00	2026-07-24 13:41:44.759428	Chuyển khoản 19	TXN202607038	COMPLETED	TRANSFER	\N	3	\N	\N
78	19000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.759428	Nhận tiền 19	TXN202607039	COMPLETED	DEPOSIT	3	\N	\N	\N
79	10000000.00	129500000.00	130000000.00	2026-07-24 13:41:44.761287	Chuyển khoản 20	TXN202607040	COMPLETED	TRANSFER	\N	3	\N	\N
80	20000000.00	129500000.00	128500000.00	2026-07-24 13:41:44.762298	Nhận tiền 20	TXN202607041	COMPLETED	DEPOSIT	3	\N	\N	\N
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, created_at, email, full_name, is_active, password, phone_number, role, updated_at, username, address, avatar_url, date_of_birth, id_number) FROM stdin;
2	2026-07-24 13:41:44.697235	khanhngoc@mbbank.vn	Lê Khánh Ngọc	t	$2a$10$1TFKYlR2j8SE//IAbUP/mu2jJT7VcytPml9S0cix07ZyTukTaijWG	0901234567	USER	2026-07-24 13:41:44.697235	khanhngoc	\N	\N	\N	\N
\.


--
-- Name: accounts_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.accounts_id_seq', 4, true);


--
-- Name: cards_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cards_id_seq', 6, true);


--
-- Name: loans_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.loans_id_seq', 4, true);


--
-- Name: notifications_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.notifications_id_seq', 20, true);


--
-- Name: savings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.savings_id_seq', 4, true);


--
-- Name: transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transactions_id_seq', 80, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 2, true);


--
-- Name: accounts accounts_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT accounts_pkey PRIMARY KEY (id);


--
-- Name: cards cards_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT cards_pkey PRIMARY KEY (id);


--
-- Name: loans loans_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loans
    ADD CONSTRAINT loans_pkey PRIMARY KEY (id);


--
-- Name: notifications notifications_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT notifications_pkey PRIMARY KEY (id);


--
-- Name: savings savings_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.savings
    ADD CONSTRAINT savings_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: accounts uk6kplolsdtr3slnvx97xsy2kc8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT uk6kplolsdtr3slnvx97xsy2kc8 UNIQUE (account_number);


--
-- Name: savings uk7nh73echyviwoymasiqduu5up; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.savings
    ADD CONSTRAINT uk7nh73echyviwoymasiqduu5up UNIQUE (saving_code);


--
-- Name: loans ukjougke3pq9pnnxcedjqodboq8; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loans
    ADD CONSTRAINT ukjougke3pq9pnnxcedjqodboq8 UNIQUE (loan_code);


--
-- Name: transactions ukq0y5v03ic3j1v5tyx1dt1ufjs; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT ukq0y5v03ic3j1v5tyx1dt1ufjs UNIQUE (reference_code);


--
-- Name: cards ukqualp9iflk959u561wanavuj1; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT ukqualp9iflk959u561wanavuj1 UNIQUE (card_number);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: transactions fk5598b948ilps8u4o3qvfo4j52; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fk5598b948ilps8u4o3qvfo4j52 FOREIGN KEY (destination_account_id) REFERENCES public.accounts(id);


--
-- Name: loans fk6xxlcjc0rqtn5nq28vjnx5t9d; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.loans
    ADD CONSTRAINT fk6xxlcjc0rqtn5nq28vjnx5t9d FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: notifications fk9y21adhxn0ayjhfocscqox7bh; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.notifications
    ADD CONSTRAINT fk9y21adhxn0ayjhfocscqox7bh FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: savings fkbj5iiqpw46u7bbkb1gdpl0d25; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.savings
    ADD CONSTRAINT fkbj5iiqpw46u7bbkb1gdpl0d25 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: cards fkcmanafgwbibfijy2o5isfk3d5; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cards
    ADD CONSTRAINT fkcmanafgwbibfijy2o5isfk3d5 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: accounts fknjuop33mo69pd79ctplkck40n; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.accounts
    ADD CONSTRAINT fknjuop33mo69pd79ctplkck40n FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: transactions fkr5dnv4t6f45ltol1wu5u27cqu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkr5dnv4t6f45ltol1wu5u27cqu FOREIGN KEY (source_account_id) REFERENCES public.accounts(id);


--
-- PostgreSQL database dump complete
--

\unrestrict e9vjYABteOfhgXdn3CsQI1lhAlMraOpB2SEKCwimllYk1HYVd3IKkAGpc7B0tw6

